name: sport_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  shared_preferences: ^2.3.2

  english_words: ^4.0.0
  provider: ^6.0.0
  logger: ^2.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true